### ISSUE TITLE
Test failures on i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by cuviper** [huonw/primal#14]
As seen in https://github.com/huonw/primal/pull/13#issuecomment-346479095

```
---- streaming::primes::benches::iterate_huge stdout ----
	thread 'streaming::primes::benches::iterate_huge' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20

---- streaming::primes::tests::equality stdout ----
	thread 'streaming::primes::tests::equality' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
```

I've bisected this to commit c7014598e08ac2982948eb4aade16aed316bfb0c, but I'm not yet sure what's wrong.

**Comment by cuviper** [comment]
Now fixed by #13.
