### ISSUE TITLE
tests failing on i386 architecture: panicked at 'attempt to add with overflow'

### ISSUE THREAD

**Issue by tenzap** [huonw/primal#60]
While trying to build the debian package of primal-sieve on i386 architecture it was found that some tests are failing.
There is no issue on amd64, arm64, riscv64.

Command:
`103s debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'test', '--verbose', '--verbose', '-j2', '--target', 'i686-unknown-linux-gnu', '--all-targets', '--all-features'],) {}`

Result:
 ```
251s     Finished test [unoptimized + debuginfo] target(s) in 2m 28s
251s      Running `/tmp/tmp.2cYLpy0GVS/target/i686-unknown-linux-gnu/debug/deps/primal_sieve-cef82c24fd59d89c`
251s 
251s running 26 tests
251s test sieve::tests::factor ... ok
251s test sieve::tests::factor_failures ... ok
251s test sieve::tests::factor_overflow ... ok
251s test sieve::tests::factor_compare ... ok
252s test sieve::tests::nth_prime ... ok
252s test sieve::tests::is_prime ... ok
252s test sieve::tests::prime_pi_sieve_limit ... ok
252s test sieve::tests::primes_from_count ... ok
252s test sieve::tests::primes_from_equality ... ok
252s test sieve::tests::primes_from_no_overrun ... ok
252s test sieve::tests::primes_from_smoke ... ok
252s test sieve::tests::small ... ok
252s test sieve::tests::sum_primes ... ok
258s test sieve::tests::prime_pi ... ok
261s test sieve::tests::upper_bound ... ok
261s test streaming::primes::tests::equality ... ok
307s test sieve::tests::u32_primes ... FAILED
309s test streaming::primes::tests::fold - should panic ... ok
311s test streaming::tests::nth_prime ... ok
321s test streaming::primes::tests::equality_huge has been running for over 60 seconds
365s test streaming::tests::nth_prime_huge ... ok
372s test streaming::tests::prime_pi ... ok
425s test streaming::tests::prime_pi_huge ... ok
430s test streaming::tests::prime_pi_issue_48 ... ok
431s test streaming::tests::prime_pi_seg_len ... ok
432s test streaming::tests::test ... ok
437s test streaming::primes::tests::equality_huge ... FAILED
437s 
437s failures:
437s 
437s ---- sieve::tests::u32_primes stdout ----
437s thread 'sieve::tests::u32_primes' panicked at 'attempt to add with overflow', src/sieve.rs:361:25
437s stack backtrace:
437s    0: rust_begin_unwind
437s              at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
437s    1: core::panicking::panic_fmt
437s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
437s    2: core::panicking::panic
437s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:117:5
437s    3: primal_sieve::sieve::Sieve::primes_from
437s              at ./src/sieve.rs:361:25
437s    4: primal_sieve::sieve::tests::u32_primes
437s              at ./src/sieve.rs:782:20
437s    5: primal_sieve::sieve::tests::u32_primes::{{closure}}
437s              at ./src/sieve.rs:775:21
437s    6: core::ops::function::FnOnce::call_once
437s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
437s    7: core::ops::function::FnOnce::call_once
437s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
437s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
437s 
437s ---- streaming::primes::tests::equality_huge stdout ----
437s thread 'streaming::primes::tests::equality_huge' panicked at 'attempt to add with overflow', src/sieve.rs:407:17
437s stack backtrace:
437s    0: rust_begin_unwind
437s              at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
437s    1: core::panicking::panic_fmt
437s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
437s    2: core::panicking::panic
437s              at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:117:5
437s    3: primal_sieve::sieve::SievePrimes::advance_ones
437s              at ./src/sieve.rs:407:17
437s    4: <primal_sieve::sieve::SievePrimes as core::iter::traits::iterator::Iterator>::next
437s              at ./src/sieve.rs:469:17
437s    5: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
437s              at /usr/src/rustc-1.70.0/library/core/src/iter/adapters/take_while.rs:46:21
437s    6: <core::iter::adapters::zip::Zip<A,B> as core::iter::adapters::zip::ZipImpl<A,B>>::next
437s              at /usr/src/rustc-1.70.0/library/core/src/iter/adapters/zip.rs:154:21
437s    7: <core::iter::adapters::zip::Zip<A,B> as core::iter::traits::iterator::Iterator>::next
437s              at /usr/src/rustc-1.70.0/library/core/src/iter/adapters/zip.rs:84:9
437s    8: primal_sieve::streaming::primes::tests::check_equality
437s              at ./src/streaming/primes.rs:193:23
437s    9: primal_sieve::streaming::primes::tests::equality_huge
437s              at ./src/streaming/primes.rs:213:9
437s   10: primal_sieve::streaming::primes::tests::equality_huge::{{closure}}
437s              at ./src/streaming/primes.rs:206:24
437s   11: core::ops::function::FnOnce::call_once
437s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
437s   12: core::ops::function::FnOnce::call_once
437s              at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
437s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
437s 
437s 
437s failures:
437s     sieve::tests::u32_primes
437s     streaming::primes::tests::equality_huge
437s 
437s test result: FAILED. 24 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 186.36s
437s 
437s error: test failed, to rerun pass `--lib`
```

**Comment by cuviper** [comment]
Ah, I see -- we do include `nightly-i686` in CI, but these `feature = "slow_tests"` are only run in `--release`, which wraps this overflow. PR incoming...

**Comment by cuviper** [comment]
If you test with `--all-features`, that includes an `"unstable"` feature that enables this inline assembly. Maybe you should just patch that feature out in your package?

(We should also reevaluate if that code is actually helpful at all...)
